###Obtener todos los empleados
GET http://localhost:3000/api/empleados

###Obtener un empleado especificos
GET http://localhost:3000/api/empleados/1

###Registrar un nuevo empleado
POST http://localhost:3000/api/empleados
Content-Type: application/json

{
  "id_rol_emp": 2,
  "nombre": "Nuevo empleado",
  "celular": "999444111"
}

###Actualizar datos de empleado
PATCH http://localhost:3000/api/empleados/3
Content-Type: application/json

{
  "nombre": "Empleado editado",
  "celular": "111222333"
}

###Eliminar empleado
DELETE http://localhost:3000/api/empleados/4




###Productos:
###Obtener todos los productos
GET http://localhost:3000/productos

###Obtener un producto especifico
GET http://localhost:3000/productos/2

###Registrar un nuevo producto
POST http://localhost:3000/productos
Content-Type: application/json

{
  "nombre": "Nuevo producto 2",
  "descripcion": "descripcion nueva",
  "costo": 100.2,
  "precio": 140.9,
  "stock": 11
}

###Actualizar datos de producto
PATCH http://localhost:3000/productos/3
Content-Type: application/json

{
  "descripcion": "descripcion editada",
  "precio": 99.00
}

###Eliminar producto
DELETE http://localhost:3000/productos/4