###Obtener todos los empleados
GET http://localhost:3000/empleados

###Obtener un empleado especificos
GET http://localhost:3000/empleados/1

###Registrar un nuevo empleado
POST http://localhost:3000/empleados
Content-Type: application/json

{
  "id_rol_emp": 2,
  "nombre": "Nuevo empleado",
  "celular": "999444111"
}

###Actualizar datos de empleado
PATCH http://localhost:3000/empleados/3
Content-Type: application/json

{
  "nombre": "Empleado editado",
  "celular": "111222333"
}

###Eliminar empleado
DELETE http://localhost:3000/empleados/4




###Productos:
###Obtener todos los productos
GET http://localhost:3000/productos

###Obtener un producto especifico
GET http://localhost:3000/productos/13

###Registrar un nuevo producto
POST http://localhost:3000/productos
Content-Type: application/json

{
  "prd_nombre": "Celula222r",
  "prd_precio": 600.00,
  "prd_descp": "Celular Nokia 2004",
  "prd_stock": 115
}

###Actualizar datos de producto
PATCH http://localhost:3000/productos/13
Content-Type: application/json

{
  "prd_descp": "Nueva descripcion",
  "prd_precio": 111.00
}

###Eliminar producto
DELETE http://localhost:3000/productos/14